### ISSUE TITLE
One Click Remote Desktop App Already Exists

### ISSUE THREAD

**Issue by pcbowers** [Divide-By-0/app-ideas-people-would-use#2]
I don't know what you do when you find an app that does some of this functionality. However, I have used [Chrome Remote Desktop](https://remotedesktop.google.com/?pli=1) for a while now, and it's only getting better. As long as you have Chrome, it's a single click to install an app, and then an access code to connect. You can do it for your own computer too and connect via your phone if you want, though I have regularly done it with my grandparents so that I can help them fix problems with their computer from afar.

**Comment by Divide-By-0** [comment]
I've seen that, and tried it for this purpose. But the codes + having to sign in is honestly too much; i really just want like a "Visit this link and consent to give me access to your computer" type of thing (which would be malware without the consent button).
