### ISSUE TITLE
An impossible task?

### ISSUE THREAD

**Issue by alexgurr** [Divide-By-0/app-ideas-people-would-use#3]
> A program where you can put in a song or artist, and it finds friends who have listened to that artist/song (by # of occurrences in their public playlists).
This is surprisingly highly requested, see thread 1, thread 2, and thread 3.

Having spent several hours on this, I've deemed it impossible. There's one core Spotify API that's needed that doesn't exist which **is the ability to get the friends list of the user**. if you don't know the user's friends or who they're following, you cannot get access to public playlists for those people. 

The API `/v1/me/following` only supports retrieving artists right now.

The only thing I found is a Spotify internal API that _does_ work, but needs an internal cookie the user would have to copy using developer tools (making the point of entry hard and therefore pointless). 

Let me know if you need any more information. This is, of course, assuming the music application is Spotify.

**Comment by Divide-By-0** [comment]
Don't Chrome extensions have access to such private cookie data?

Is it possible to connect to my Facebook account instead, and from there it finds each of the users individually?

**Comment by alexgurr** [comment]
I think the chrome extension idea is actually pretty good, then you wouldn't even need to connect to Spotify.
